# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 09:00
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emocion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palabra', models.CharField(blank=True, default='', max_length=30)),
                ('porcentajes', models.CharField(max_length=100, validators=[(django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.'), '0,17,33,50,67,83,100', None)])),
                ('emocion_mayor', models.CharField(choices=[(0, 'TRISTEZA'), (1, 'MIEDO'), (2, 'ALEGRIA'), (3, 'ENFADO'), (4, 'SORPRESA'), (5, 'NEUTRAL')], default='NEUTRAL', max_length=10)),
            ],
            options={
                'ordering': ('palabra',),
            },
        ),
    ]
