# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 11:09
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('emocion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emocion',
            name='porcentajes',
            field=models.CharField(max_length=100, validators=[[(django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.'), '0,17,33,50,67,83,100', None)]]),
        ),
    ]
